# Generated by Django 2.1.5 on 2019-02-04 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.datetime(2019, 2, 4, 12, 20, 1, 41009, tzinfo=utc))),
                ('time_out', models.DateField(blank=True, null=True)),
                ('access_key', models.CharField(max_length=10)),
            ],
        ),
    ]
