# Generated by Django 2.1.5 on 2019-02-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasteSiteApp', '0004_auto_20190205_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='created_on',
        ),
    ]
