# Generated by Django 2.1.5 on 2019-02-05 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PasteSiteApp', '0005_remove_paste_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 2, 5, 13, 5, 25, 340275, tzinfo=utc)),
        ),
    ]
