# Generated by Django 2.1.5 on 2019-02-05 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PasteSiteApp', '0006_paste_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
