# Generated by Django 2.1.5 on 2019-02-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasteSiteApp', '0008_auto_20190205_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paste',
            options={'ordering': ['-created_on', 'access_key']},
        ),
    ]
